colors:
  # Default colors
  primary:
    background: '0x2c2c2c'
    foreground: '0xd6d6d6'

    dim_foreground:    '0xdbdbdb'
    bright_foreground: '0xd9d9d9'
    dim_background:    '0x202020' # not sure
    bright_background: '0x3a3a3a' # not sure

  # Cursor colors
  cursor:
    text:   '0x2c2c2c'
    cursor: '0xd9d9d9'

  # Normal colors
  normal:
    black:   '0x1c1c1c'
    red:     '0xbc5653'
    green:   '0x909d63'
    yellow:  '0xebc17a'
    blue:    '0x7eaac7'
    magenta: '0xaa6292'
    cyan:    '0x86d3ce'
    white:   '0xcacaca'

  # Bright colors
  bright:
    black:   '0x636363'
    red:     '0xbc5653'
    green:   '0x909d63'
    yellow:  '0xebc17a'
    blue:    '0x7eaac7'
    magenta: '0xaa6292'
    cyan:    '0x86d3ce'
    white:   '0xf7f7f7'

  # Dim colors
  dim:
    black:   '0x232323'
    red:     '0x74423f'
    green:   '0x5e6547'
    yellow:  '0x8b7653'
    blue:    '0x556b79'
    magenta: '0x6e4962'
    cyan:    '0x5c8482'
    white:   '0x828282'

font:
  normal:
    family: monospace
    style: Regular

  bold:
    family: monospace
    style: Bold

  italic:
    family: monospace
    style: Italic

  bold_italic:
    family: monospace
    style: Bold Italic

  size: 9
  offset:
    x: -1
    y: -1

# background_opacity: 0.92

#bell:
#  animation: EaseOutExpo
#  duration: 200
#  color: '0xff0000'
  
  # Values for `animation`:
  #   - Ease
  #   - EaseOut
  #   - EaseOutSine
  #   - EaseOutQuad
  #   - EaseOutCubic
  #   - EaseOutQuart
  #   - EaseOutQuint
  #   - EaseOutExpo
  #   - EaseOutCirc
  #   - Linear

key_bindings:
  - { key: Return,   mods: Control|Alt, action: SpawnNewInstance }
  - { key: V,   mods: Control|Shift, action: Paste}
  - { key: C,   mods: Control|Shift, action: Copy}
  - { key: K,   mods: Super, action: ScrollHalfPageUp}
  - { key: J,   mods: Super, action: ScrollHalfPageDown}
  - { key: J,   mods: Control|Alt, action: DecreaseFontSize }
  - { key: K,   mods: Control|Alt, action: IncreaseFontSize }
  - { key: H,   mods: Control|Alt, action: ResetFontSize}
  - { key: U,   mods: Control|Alt, action: ToggleViMode}
  - { key: Tab, mods: Control,        chars: "\x1b[27;5;9~" }
  - { key: Tab, mods: Control|Shift,  chars: "\x1b[27;6;9~" }
  - { key: I,   mods: Control|Alt, command: {program: "alacritty-invert-colours", args: [] }}
