lastupdatecheck: 0
recentrepos:
- /home/tris/Projects/Tests/phresh-tutorial
- /home/tris/Projects/Works/emotiv-id
- /home/tris/Projects/Works/emotiv-openid-connect
- /home/tris/Projects/Works/cerebrum
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
ignorewhitespaceindiffview: false
